alias: "Xbox One started from Harmony Hub"
trigger:
  platform: state
  entity_id: remote.harmony_hub
condition:
  condition: template
  value_template: '{{ trigger.to_state.attributes.current_activity == "Xbox One" }}'
action:
  service: input_select.select_option
  entity_id: input_select.harmony
  data:
    option: "Xbox One"