############################################################
#
# Home Assistant Main Configuration File
#
############################################################
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  name: HOME
  customize: !include_dir_merge_named customizations
  customize_glob:
    "light.*":
      custom_ui_state_card: custom_light
      state_card_mode: single-line
      slider_theme:
        min: 10
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

http:
  api_password: !secret http_password
tts:
  platform: google


####################################################
#                                                  
#                     Enables             
#                                                  
####################################################
updater:
discovery:
  ignore:
    - samsung_tv
conversation:

####################################################
#                                                  
#                     History             
#                                                  
####################################################


history:
  include: 
    entities:
    - device_tracker.joe_joe
    - device_tracker.c_43b2b5b5027ba2db
    - device_tracker.c_071c1cf0d26b1be3
    - sensor.work_to_home
    - sensor.home_to_work
    - sensor.phone_to_home
    - sensor.pihole
    - sensor.hallway_thermostat_danest_temperature
    - sensor.water_temperature
    - sensor.living_room_nest_protect_co_status
    - sensor.downstairs_nest_protect_co_status
    - sensor.living_room_nest_protect_smoke_status
    - sensor.downstairs_nest_protect_smoke_status
    - sensor.ups_battery
    - sensor.ups_input_voltage
    - sensor.ups_load
    - sensor.ups_nominal_input_voltage
    - sensor.ups_nominal_output_power
    - sensor.ups_status
    - lock.backdoor_lock
    - sensor.backdoor
    - lock.frontdoor_lock
    - sensor.frontdoor

recorder:
  purge_days: 3
  db_url: !secret db_url
  include: 
    entities:
    - device_tracker.joe_joe
    - device_tracker.c_43b2b5b5027ba2db
    - device_tracker.c_071c1cf0d26b1be3
    - sensor.work_to_home
    - sensor.home_to_work
    - sensor.phone_to_home
    - sensor.pihole
    - sensor.hallway_thermostat_danest_temperature
    - sensor.water_temperature
    - sensor.living_room_nest_protect_co_status
    - sensor.downstairs_nest_protect_co_status
    - sensor.living_room_nest_protect_smoke_status
    - sensor.downstairs_nest_protect_smoke_status
    - sensor.ups_battery
    - sensor.ups_input_voltage
    - sensor.ups_load
    - sensor.ups_nominal_input_voltage
    - sensor.ups_nominal_output_power
    - sensor.ups_status
    - sensor.shopscraft_pvp
    - sensor.shopscraft_creative
    - sensor.shopscraft_minigames
    - lock.backdoor_lock
    - sensor.backdoor
    - lock.frontdoor_lock
    - sensor.frontdoor

############################################################
#
# Components
#
############################################################

mqtt:
  broker: localhost
  client_id: hass
  username: pi
  password: !secret http_password
remote:
  platform: harmony
  name: Harmony Hub
  host: !secret harmony
wink:
  access_token: !secret wink_at
  user_agent: Manufacturer/Home-Assistant WinkAndroid/4
nest:
  client_id: !secret nest_ci
  client_secret: !secret nest_cs
apcupsd:
  host: !secret ups
sun:
zeroconf:
frontend:

############################################################
#
#                       Includes
#
############################################################

zone: !include_dir_list zones
automation: !include_dir_list automations
notify: !include_dir_list notifications
switch: !include_dir_list switches
scene: !include_dir_list scenes
device_tracker: !include_dir_merge_list trackers
lock: !include_dir_list locks
camera: !include_dir_list cameras
script: !include_dir_named scripts
sensor: !include_dir_list sensors
group: !include groups.yaml
wemo: !include wemo.yaml
light: !include hue.yaml
panel_iframe: !include panels.yaml
media_player: !include media.yaml
logbook: !include_dir_merge_named logbook/

############################################################
#
#                       Inputs
#
############################################################


input_select: !include input-selects.yaml
# input_slider: !include input-sliders.yaml


############################################################
#
#                       Customize
#
############################################################


############################################################
#
#                       Weblinks
#
############################################################


weblink:
  entities:
    - name: Minecraft Admin
      url: !secret MC_url
      icon: mdi:minecraft
    - name: Minecraft 2 Admin
      url: !secret MC2_url
      icon: mdi:minecraft
    - name: Minecraft Map
      url: !secret MC_map
      icon: mdi:minecraft
    - name: Minecraft 2 Map
      url: !secret MC_map2
      icon: mdi:minecraft
    - name: Storage
      url: !secret storage
      icon: mdi:server
    - name: Sickrage
      url: !secret sickrage
      icon: mdi:television
    - name: Torrents
      url: !secret torrents
      icon: mdi:download
    - name: Pi-Hole
      url: !secret pihole
      icon: mdi:raspberrypi
    - name: Security
      url: !secret Security
      icon: mdi:camera

