alias: Brightness Bedroom
trigger:
  platform: state
  entity_id: input_slider.brightness_bedroom
action:
  service: light.turn_on
  data:
    entity_id:
      - light.bedroom_1
      - light.bedroom_2
      - light.bedroom_3
  data_template:
    brightness: '{{ states( "input_slider.brightness_bedroom" )|round( 0 ) }}'