alias: Update notifications
trigger:
  platform: state
  entity_id: updater.updater
action:
  - service: notify.pushbullet
    data:
      message: 'There is a new release of Home Assistant available.'
